# -*- coding: utf-8 -*-
"""Projeto de Parceria | Semantix v1.6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChYyJhJxb498-EI4pHNF6wd7-_qHrPuQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

pd.set_option('display.max_columns', None)

df = pd.read_csv('dados_tratados_censo_2024_v2.csv')

df.head()

df.shape
df.info()

df.isnull().sum() #Verifica se há dados nulos

df_ens_medio = df[df['MATRICULAS_ENSINO_MEDIO'] > 0]

print('Número de escolas com Ensino Médio\n', df_ens_medio.shape)

total_escolas = df_ens_medio.shape[0]
total_publicas = df_ens_medio[df_ens_medio['TIPO_ESCOLA'] == 'Pública'].shape[0]
total_particulares = df_ens_medio[df_ens_medio['TIPO_ESCOLA'] == 'Particular'].shape[0]

print("Total de Escolas", total_escolas)
print(f'% Escolas Públicas: {total_publicas / total_escolas:.2%}')
print(f'% Escolas Particulares: {total_particulares / total_escolas:.2%}') #Verifica a quantidade de escolas e a porcentagem de cada uma

localizacao = df_ens_medio['LOCALIZACAO'].value_counts(normalize=True) * 100
print('Tipo de Localização:')
for loc, pct in localizacao.items():
    print(f' - {loc}: {pct:.2f}%') #Verifica a porcentagem das localizaçoes das escolas

df_ens_medio[['MATRICULAS_ENSINO_MEDIO', 'PREFESSORES_ENS_MED', 'TURMAS_ENSINO_MEDIO']].mean().round(2) #Traz a média de matriculas no ensino médio, professores e quantidade de turmas

df_ens_medio["ALUNOS_POR_PROF"] = df_ens_medio["MATRICULAS_ENSINO_MEDIO"] / df_ens_medio["PREFESSORES_ENS_MED"]
df_ens_medio["ALUNOS_POR_TURMA"] = df_ens_medio["MATRICULAS_ENSINO_MEDIO"] / df_ens_medio["TURMAS_ENSINO_MEDIO"]

df_ens_medio[["ALUNOS_POR_PROF", "ALUNOS_POR_TURMA"]].mean()

#Média de alunos por professor e por turma

infra_cols = ["QUADRA_ESPORTES", "REFEITORIO", "COMPUTADOR", "INTERNET"]
infra_pct = df_ens_medio[infra_cols].apply(lambda x: (x == "Sim").mean() * 100)

print("Porcentagem de Infraestrutura:\n")
for col, pct in infra_pct.items():
    print(f" - {col}: {pct:.2f}%") #Infraestrutura da escolas cadastradas

df_ens_medio["REGIAO"].value_counts()

#Número de escolas por região

df_ens_medio['ID_UF'].value_counts() #Quantidade de turmas de ensino médio por estado

infra_por_regiao = df_ens_medio.groupby("REGIAO")[infra_cols].apply(lambda x: (x == "Sim").sum())
print(infra_por_regiao) #Infra estrutura por região

total_por_regiao = df_ens_medio.groupby("REGIAO").size()
infra_pct = infra_por_regiao.div(total_por_regiao, axis=0) * 100
infra_pct = infra_pct.round(2)

print("\nPercentual de escolas com infraestrutura por região (%):\n")
print(infra_pct)

# A região Nordeste apresenta o menor percentual de escolas com refeitório (40%). Já o Sudeste possui a maior proporção de escolas com quadra de esportes (86%). Esses dados evidenciam desigualdades regionais na infraestrutura escolar que podem impactar a permanência dos alunos.

df_ens_medio.groupby('INTERNET')['MATRICULAS_ENSINO_MEDIO'].count().round(2)
#Quantidade de escolas que possuem acessoa a internet comparado ao número de matrículas

df_ens_medio.groupby(['ID_UF', 'TIPO_ESCOLA']).size().unstack().fillna(0).apply(lambda x: x / x.sum() * 100, axis=1).round(2)
#Proporção do tipo de escola nos estados brasileiros

df_ens_medio.groupby("LOCALIZACAO")[infra_cols].apply(lambda x: (x == "Sim").sum()).T
#Soma das estruturas de acesso entre as escolas Rural e Urbana

