# -*- coding: utf-8 -*-
"""Projeto de Parceria | Semantix v1.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIg-1YbdhUh472qwIzLyY_P6Osn_4kfB
"""

pip install pyspark

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.storagelevel import StorageLevel

spark = SparkSession.builder.getOrCreate()

df_saeb_com_respostas = spark.read.csv('dados_saeb_evadidos_com_respostas.csv', header=True, inferSchema=True)

df_saeb_com_respostas.show()

df_saeb_com_respostas.printSchema()

df_reprovado = df_saeb_com_respostas.groupBy('REPROVADO').count().show()

df_abandono = df_saeb_com_respostas.groupBy('ABANDONO').count().show()

df_tipo_escola = df_saeb_com_respostas.groupBy('TIPO_ESCOLA').count().show()

df_idade = df_saeb_com_respostas.groupBy('IDADE').count().show()

df_trabalho = df_saeb_com_respostas.groupBy('ALUNO_TRABALHA').count().show()

df_saeb_sem_respostas = spark.read.csv('dados_saeb_evadidos_sem_respostas.csv', header=True, inferSchema=True)

df_saeb_sem_respostas.show()

df_sem_respostas_regiao = df_saeb_sem_respostas.groupBy('REGIAO').count().show()

df_sem_respostas_uf = df_saeb_sem_respostas.groupBy('ID_UF').count().show(28)