# -*- coding: utf-8 -*-
"""Projeto de Parceria | Semantix v1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRpFteENdOXyI9FgzZRu1eeClA79Uokj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

pd.set_option('display.max_columns', None)

df = pd.read_csv('microdados_ed_basica_2024.csv', encoding='ISO-8859-1', sep=';', low_memory=False)

print('Shape do DataFrame:', df.shape)
print('\nColunas do DataFrame:', df.columns.tolist())

print('Tipo de Dados:\n', df.dtypes) #Verifica os tipos de dados na planilha

print('\nValores Nulos:\n', df.isnull().sum()) #Soma a quantidade de valores nulos

df.info()

df.isnull().sum().sort_values(ascending=False).head(20) #Verifica a quantidade de valores nulos por coluna

colunas_util = [
    'NO_REGIAO', 'NO_UF', 'SG_UF', 'NO_MUNICIPIO', 'NO_ENTIDADE', 'TP_DEPENDENCIA', 'TP_LOCALIZACAO', 'TP_SITUACAO_FUNCIONAMENTO',
    'IN_QUADRA_ESPORTES', 'IN_REFEITORIO', 'IN_COMPUTADOR', 'IN_INTERNET', 'QT_MAT_MED', 'QT_MAT_MED_INT', 'QT_DOC_MED', 'QT_TUR_MED'

]

df_final = df[colunas_util].copy()
print('Shape DataFrame Final:\n', df_final.shape)
print(df_final.head(5)) #define as colunas que serão utilizadas da tabela para melhor análise

print('Dados Nulos:\n', df_final.isnull().sum())

df_final = df_final.dropna(subset=['QT_MAT_MED', 'QT_MAT_MED_INT', 'QT_DOC_MED', 'QT_TUR_MED'])

print('Dados Nulos após limpeza:\n', df_final.isnull().sum())

df_final.info()

df_final.to_csv('dados_tratados_censo_2024.csv', index=False)